name: bloomsplash
description: "A beautiful wallpaper application"
publish_to: "none"
version: 0.2.2+6
license: "AGPL-3.0"

environment:
  sdk: ^3.7.2
  flutter: 3.32.2

dependencies:
  # --- Flutter SDK ---
  flutter:
    sdk: flutter

  # --- UI & Design ---
  palette_generator: ^0.3.3+7
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  cached_network_image: ^3.4.1
  flutter_keyboard_visibility: ^6.0.0

  # --- Media & Image ---
  screenshot: ^3.0.0
  image_picker: ^1.1.2
  async_wallpaper:
    git:
      url: https://github.com/IshuSinghSE/async_wallpaper.git
      ref: main

  # --- Permissions & Device Info ---
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.3
  google_api_availability: ^5.0.1
  media_scanner: ^2.2.0

  # --- Networking & File Handling ---
  http: ^1.4.0
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5

  # --- Local Storage & Utilities ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.2
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  provider: ^6.1.4
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.2

  # --- Firebase ---
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+5
  firebase_analytics: ^11.4.6
  firebase_messaging: ^15.2.9
  firebase_performance: ^0.10.1+7
  google_sign_in: ^6.3.0

  # --- In-App Review & Notifications ---
  in_app_review: ^2.0.10
  flutter_local_notifications: ^19.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/


flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#121212"
  image: "assets/icons/ic_launcher.png"


  android_12:
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"

    color_dark: "#121212" # Soft black shade for dark theme
    icon_background_color_dark: "#121212"
    image: "assets/icons/ic_launcher.png"

  
  ios: false
  web: false

flutter_icons:
        android: true
        ios: false
        remove_alpha_ios: true
        icon: "assets/icons/ic_launcher.png"
        image_path: "assets/icons/ic_launcher.png"
        adaptive_icon_background: "#FFFFFF" # Only for Android 8.0+
        adaptive_icon_foreground: "assets/icons/ic_launcher.png" # Only for Android 8.0+
        adaptive_icon_monochrome: "assets/icons/ic_launcher_monochrome.png" # Only for Android 8.0+

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
