name: bloomsplash
description: "A beautiful wallpaper application"
publish_to: "none"
version: 0.1.2

environment:
  sdk: ^3.7.2

dependencies:
  # --- Flutter SDK ---
  flutter:
    sdk: flutter

  # --- UI and Design ---
  cupertino_icons: ^1.0.8
  glassmorphism: ^3.0.0
  palette_generator: ^0.3.3+7

  # --- Networking and File Handling ---
  dio: ^5.0.0
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  android_content_provider: ^0.5.2
  media_scanner: ^2.2.0
  http: ^1.4.0

  # --- Media and Permissions ---
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.3.3
  flutter_keyboard_visibility: ^6.0.0
  cached_network_image: ^3.4.1

  # --- Image Processing ---
  image: 3.2.2

  # --- Local Storage ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.2

  # --- Firebase ---
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  firebase_app_check: ^0.3.2+5
  firebase_analytics: ^11.4.6


  # --- Utilities ---
  provider: ^6.1.4
  google_sign_in: ^6.3.0
  flutter_native_splash: ^2.2.16
  fluttertoast: ^8.2.12
  google_api_availability: ^5.0.1

  # --- Wallpaper ---
  async_wallpaper:
    git:
      url: https://github.com/IshuSinghSE/async_wallpaper.git
      ref: main
  shimmer: ^3.0.0
  flutter_launcher_icons: ^0.11.0
  firebase_performance: ^0.10.1+7
  # blurhash: ^1.2.0
  # flutter_blurhash: ^0.9.1

flutter_icons:
        android: true
        ios: true
        remove_alpha_ios: true
        image_path: "assets/icons/ic_launcher_monochrome.png"
        adaptive_icon_background: "#FFFFFF" # Only for Android 8.0+
        adaptive_icon_foreground: "assets/icons/ic_launcher.png" # Only for Android 8.0+
        adaptive_icon_monochrome: "assets/icons/ic_launcher_monochrome.png" # Only for Android 8.0+

dev_dependencies:
  # --- Dev Dependencies ---
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
