name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# The following section is specific to Flutter.
dependencies:
  flutter:
    sdk: flutter

# 
  cupertino_icons: ^1.0.8
  palette_generator: ^0.3.3+6
  glassmorphism: ^3.0.0
  dio: ^5.0.0
  path_provider: ^2.0.11
  android_content_provider: ^0.5.2
  media_scanner: ^2.2.0
  async_wallpaper:
    git:
      url: https://github.com/IshuSinghSE/async_wallpaper.git
      ref: main
  flutter_cache_manager: ^3.4.1
  provider: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # wallpaper_manager_flutter: ^1.0.1
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add custom platform-specific implementations of your plugin, add the
  assets:
    - assets/avatar/
    - assets/sample/
    - assets/
    - assets/wallpapers.json

  # To add custom platform-specific implementations of your plugin, add the
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
