/// Exportable tag list for use in search page UI and elsewhere
const List<String> kTagList = [
  'dark',
  'colorful',
  'mountain',
  'minimal',
  'nature',
  'space',
  'food',
  'abstract',
  'art',
  'technology',
  'city',
  'landscape',
  'portrait',
  'animals',
  'travel',
  'water',
  'vintage',
  'black and white',
  'sunset',
  'flowers',
  'music',
  'sports',
  'fashion',
  'architecture',
  'cars',
  'food',
  'night',
];
