default_platform(:android)

platform :android do
  desc "Deploy to closed testing"
  lane :closed_release do
    upload_to_play_store(
      track: 'closed', # use 'internal' if you want internal testing
      json_key: 'fastlane/google-play-key.json',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
