name: Auto Merge Release PR

on:
  pull_request:
    branches:
      - main
    types:
      - labeled
      - synchronize
      - opened
      - reopened
      - ready_for_review

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
